### ISSUE TITLE
-

### ISSUE THREAD

**Issue by kamishadow** [Yirain/btctool#1]
address.c
use switch-case or a list instead of so much 'if', plz.

**Comment by nakululusatuva** [comment]
Do you mean "int8_t selector(int32_t item)"? @kamishadow

**Comment by nakululusatuva** [comment]
Fixed

**Comment by kamishadow** [comment]
the same in btctool.c
use a list or switch would be clearer.
and maybe you can define error code instead -1, -2~

**Comment by kamishadow** [comment]
:)

**Comment by nakululusatuva** [comment]
Nice advice, thanks a lot :)
